CloneUtility/Controllers/DVStreamController.cs
using CloneUtility.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Management.Automation;
using System.Management.Automation.Runspaces;
using System.Security;
using System.Web;
using System.Web.Mvc;

namespace CloneUtility.Controllers
{
    public class DVStreamController : Controller
    {

        public ActionResult Index()
        {
            ViewBag.Title = "DVStreamUtility";

            return View();
        }

        public ActionResult DbClone()
        {
            ViewBag.Title = "DVStreamUtility";

            return View();
        }

        public ActionResult Dsn()
        {
            ViewBag.Title = "DVStreamUtility";

            return View();
        }

    }

}

CloneUtility/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="cloneUtilityApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap.min.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/ng")
</head>
<body>
   <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CloneUtility (Ver:R3:11/1/2016)", "Index", "DVStream", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav nav-tabs">
                   <li>@Html.ActionLink("DVStream", "Index", "DVStream", new { area = "" }, null)</li>
                   <li>@Html.ActionLink("DataBase", "DbClone", "DVStream", new { area = "" }, null)</li>
                   <li>@Html.ActionLink("Create DSN", "Dsn", "DVStream", new { area = "" }, null)</li>
            </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>